### kace登录后携带正确token，测试该controller没有未授权(kace只有depControler的权限)，响应自定义授权异常403
POST http://localhost:8080/note-springboot/emp/1/10
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqYXZhIiwiZXhwIjoxNjY3Mjg2NDY0LCJpYXQiOjE2NjcyODQ2NjQsInVzZXJuYW1lIjoianVseSJ9.W_NJveBnmfIYR6rtp5BQckoIeOeiEjo1bkjbthnbMVo
Content-Type: application/json

{

}

### kace登录后携带错误token，测试该controller没有未认证，响应自定义认证异常401
GET http://localhost:8080/note-springboot/emp/1
token: MjEwMzMsInVzZX


### kace登录后不携带token，测试该controller没有未认证，响应自定义认证异常401
GET http://localhost:8080/note-springboot/emp/1

### kace登录后携带正确token，测试该controller全局异常，响应自定义全局异常500
GET http://localhost:8080/note-springboot/emp/globalException
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqYXZhIiwiZXhwIjoxNjY3Mjg2NDY0LCJpYXQiOjE2NjcyODQ2NjQsInVzZXJuYW1lIjoianVseSJ9.W_NJveBnmfIYR6rtp5BQckoIeOeiEjo1bkjbthnbMVo
