### 登录noby，administrator拥有所有权限
POST http://localhost:8080/note-springboot/user/login
Content-Type: application/json

{
  "username": "noby",
  "password": "123"
}

### 登录kace，user拥有dep权限
POST http://localhost:8080/note-springboot/user/login
Content-Type: application/json

{
  "username": "kace",
  "password": "123"
}

### 登录july，guste拥有emp权限
POST http://localhost:8080/note-springboot/user/login
Content-Type: application/json

{
  "username": "july",
  "password": "123"
}

### 测试
POST http://localhost:8080/note-springboot/user/login
Content-Type: application/json

{
  "username": "july",
  "password": "123"
}

### 登录noby，administrator拥有所有权限，linux
POST http://192.168.122.128:8080/note-springboot/user/login
Content-Type: application/json

{
  "username": "noby",
  "password": "123"
}


