---
server:
  port: 8081
spring:
  profiles: dev
info: 单文件(多文档)profile配置方式，dev环境
---
server:
  port: 8081
spring:
  profiles: test
info: 单文件(多文档)profile配置方式，test环境
---
server:
  port: 8081
spring:
  profiles: pro
info: 单文件(多文档)profile配置方式，pro环境
---
# 配置文件激活方式
spring:
  profiles:
    active: test
# VM options 配置方式，虚拟机配置优先级高于配置文件激活方式
# -Dspring.profiles.active=dev
# Program arguments 配置方式，命令行配置优先级高于配置文件激活方式
# --spring.profiles.active=pro

# 启动参数别名的配置，使用了该别名后，VM options 配置方式中参数可以使用-Dactive=dev代替-Dspring.profiles.active=dev
#spring:
#  profiles:
#    active: ${active:dev}