server:
  port: 8080
logging:
  level:
    priv.noby.mybatisgenerator: debug
  pattern:
    console: "[%thread] %-5level %logger{0} - %msg%n"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stage3?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/priv/noby/mybatisgenerator/dao/*.xml